// SPDX-License-Identifier: MPL-2.0

use ostd::sync::WaitQueue;
use rand::{RngCore, SeedableRng, rngs::StdRng};
use spin::Once;

use crate::{
    events::IoEvents,
    prelude::*,
    process::signal::{PollHandle, Pollee},
};

static RANDOM: Once<RandomState> = Once::new();

struct RandomState {
    inner: SpinLock<RandomInner>,
    pollee: Pollee,
    wait_queue: WaitQueue,
}

struct RandomInner {
    crng: StdRng,
    ready: bool,
}

enum RandomSeed {
    Trusted(<StdRng as SeedableRng>::Seed),
    Insecure(<StdRng as SeedableRng>::Seed),
}

impl RandomSeed {
    fn into_seed_and_ready(self) -> (<StdRng as SeedableRng>::Seed, bool) {
        match self {
            RandomSeed::Trusted(seed) => (seed, true),
            RandomSeed::Insecure(seed) => (seed, false),
        }
    }
}

/// Fills `dest` with random bytes.
///
/// The returned bytes may be based on an insecure early seed if the random
/// subsystem has not been securely initialized yet.
pub fn getrandom(dst: &mut [u8]) {
    fill_insecure(dst);
}

/// Fills `dst` with best-effort random bytes without waiting for readiness.
pub fn fill_insecure(dst: &mut [u8]) {
    RANDOM.get().unwrap().inner.lock().crng.fill_bytes(dst);
}

/// Returns whether the random subsystem has been securely initialized.
pub fn is_ready() -> bool {
    RANDOM.get().unwrap().inner.lock().ready
}

/// Polls the readiness of the secure random stream.
pub fn poll(mask: IoEvents, poller: Option<&mut PollHandle>) -> IoEvents {
    RANDOM
        .get()
        .unwrap()
        .pollee
        .poll_with(mask, poller, random_io_events)
}

/// Waits until the random subsystem has been securely initialized.
pub fn wait_until_ready() -> Result<()> {
    if is_ready() {
        return Ok(());
    }

    RANDOM
        .get()
        .unwrap()
        .wait_queue
        .pause_until(|| is_ready().then_some(()))
}

/// Returns `EAGAIN` if the random subsystem has not been securely initialized.
pub fn try_wait_until_ready() -> Result<()> {
    if is_ready() {
        return Ok(());
    }

    return_errno_with_message!(Errno::EAGAIN, "the random subsystem is not ready");
}

pub fn init() {
    // The seed used to initialize the RNG is required to be secure and unpredictable.
    let (seed, ready) = get_random_seed().into_seed_and_ready();

    RANDOM.call_once(|| RandomState {
        inner: SpinLock::new(RandomInner {
            crng: StdRng::from_seed(seed),
            ready,
        }),
        pollee: Pollee::new(),
        wait_queue: WaitQueue::new(),
    });

    if ready {
        RANDOM.get().unwrap().wait_queue.wake_all();
        RANDOM.get().unwrap().pollee.notify(IoEvents::IN);
    }
}

fn random_io_events() -> IoEvents {
    if is_ready() {
        IoEvents::IN | IoEvents::OUT
    } else {
        IoEvents::OUT
    }
}

fn get_random_seed() -> RandomSeed {
    // Prefer the hardware RNG if available.
    if let Some(seed) = read_seed_from_hardware() {
        ostd::info!("use randomness generated by hardware");
        return RandomSeed::Trusted(seed);
    }

    // x86_64: if no hardware RNG and running inside TDX, abort.
    //
    // For more details, see
    // <https://intel.github.io/ccc-linux-guest-hardening-docs/security-spec.html#randomness-inside-tdx-guest>.
    #[cfg(target_arch = "x86_64")]
    ostd::if_tdx_enabled!({
        panic!("hardware randomness is mandatory for TD guests");
    });

    // Non-x86_64: fall back to the device-tree seed if present.
    #[cfg(not(target_arch = "x86_64"))]
    if let Some(seed) = read_seed_from_device_tree() {
        ostd::info!("use randomness provided by the device tree");
        return RandomSeed::Trusted(seed);
    }

    // Some platforms (e.g., RISC-V `sifive_u`) have neither hardware
    // randomness nor randomness from the device tree. Continue with an
    // insecure early seed, but do not mark the random subsystem as ready.
    ostd::warn!("use randomness based on the timestamp, which is insecure");
    RandomSeed::Insecure(read_seed_from_timestamp())
}

fn read_seed_from_hardware() -> Option<<StdRng as SeedableRng>::Seed> {
    use ostd::arch::read_random;

    read_seed_from(read_random)
}

#[cfg(not(target_arch = "x86_64"))]
fn read_seed_from_device_tree() -> Option<<StdRng as SeedableRng>::Seed> {
    use ostd::arch::boot::DEVICE_TREE;

    DEVICE_TREE
        .get()
        .unwrap()
        .find_node("/chosen")
        .and_then(|chosen| chosen.property("rng-seed"))
        .and_then(|rng_seed| <StdRng as SeedableRng>::Seed::try_from(rng_seed.value).ok())
}

fn read_seed_from_timestamp() -> <StdRng as SeedableRng>::Seed {
    use ostd::arch::read_tsc;

    read_seed_from(|| Some(read_tsc())).unwrap()
}

fn read_seed_from(
    mut next_random: impl FnMut() -> Option<u64>,
) -> Option<<StdRng as SeedableRng>::Seed> {
    let mut seed = <StdRng as SeedableRng>::Seed::default();

    let mut chunks = seed.as_mut().chunks_exact_mut(size_of::<u64>());
    for chunk in chunks.by_ref() {
        let val = next_random()?;
        chunk.copy_from_slice(&val.to_ne_bytes());
    }
    let tail = chunks.into_remainder();
    if !tail.is_empty() {
        let val = next_random()?;
        tail.copy_from_slice(&val.to_ne_bytes()[..tail.len()]);
    }

    Some(seed)
}
