// SPDX-License-Identifier: MPL-2.0

use rand::{RngCore, SeedableRng, rngs::StdRng};
use spin::Once;

use crate::prelude::*;

static RNG: Once<SpinLock<StdRng>> = Once::new();

/// Fill `dest` with random bytes.
///
/// It's cryptographically secure, as documented in [`rand::rngs::StdRng`].
pub fn getrandom(dst: &mut [u8]) {
    RNG.get().unwrap().lock().fill_bytes(dst);
}

pub fn init() {
    // The seed used to initialize the RNG is required to be secure and unpredictable.
    let seed = get_random_seed();

    RNG.call_once(|| SpinLock::new(StdRng::from_seed(seed)));
}

fn get_random_seed() -> <StdRng as SeedableRng>::Seed {
    // Prefer the hardware RNG if available.
    if let Some(seed) = read_seed_from_hardware() {
        ostd::info!("use randomness generated by hardware");
        return seed;
    }

    // x86_64: if no hardware RNG and running inside TDX, abort.
    //
    // For more details, see
    // <https://intel.github.io/ccc-linux-guest-hardening-docs/security-spec.html#randomness-inside-tdx-guest>.
    #[cfg(target_arch = "x86_64")]
    ostd::if_tdx_enabled!({
        panic!("hardware randomness is mandatory for TD guests");
    });

    // Non-x86_64: fall back to the device-tree seed if present.
    #[cfg(not(target_arch = "x86_64"))]
    if let Some(seed) = read_seed_from_device_tree() {
        ostd::info!("use randomness provided by the device tree");
        return seed;
    }

    // Some platforms (e.g., RISC-V `sifive_u`) have neither hardware
    // randomness nor randomness from the device tree. For now, we will
    // continue with pseudorandomness.
    // TODO: Collect entropy from environment noise for better security.
    ostd::warn!("use randomness based on the timestamp, which is insecure");
    read_seed_from_timestamp()
}

fn read_seed_from_hardware() -> Option<<StdRng as SeedableRng>::Seed> {
    use ostd::arch::read_random;

    read_seed_from(read_random)
}

#[cfg(not(target_arch = "x86_64"))]
fn read_seed_from_device_tree() -> Option<<StdRng as SeedableRng>::Seed> {
    use ostd::arch::boot::DEVICE_TREE;

    DEVICE_TREE
        .get()
        .unwrap()
        .find_node("/chosen")
        .and_then(|chosen| chosen.property("rng-seed"))
        .and_then(|rng_seed| <StdRng as SeedableRng>::Seed::try_from(rng_seed.value).ok())
}

fn read_seed_from_timestamp() -> <StdRng as SeedableRng>::Seed {
    use ostd::arch::read_tsc;

    read_seed_from(|| Some(read_tsc())).unwrap()
}

fn read_seed_from(
    mut next_random: impl FnMut() -> Option<u64>,
) -> Option<<StdRng as SeedableRng>::Seed> {
    let mut seed = <StdRng as SeedableRng>::Seed::default();

    let mut chunks = seed.as_mut().chunks_exact_mut(size_of::<u64>());
    for chunk in chunks.by_ref() {
        let val = next_random()?;
        chunk.copy_from_slice(&val.to_ne_bytes());
    }
    let tail = chunks.into_remainder();
    if !tail.is_empty() {
        let val = next_random()?;
        tail.copy_from_slice(&val.to_ne_bytes()[..tail.len()]);
    }

    Some(seed)
}
