.section .text
vector0:
	push 0
	push 0
	jmp __trap_entry
vector1:
	push 0
	push 1
	jmp __trap_entry
vector2:
	push 0
	push 2
	jmp __trap_entry
vector3:
	push 0
	push 3
	jmp __trap_entry
vector4:
	push 0
	push 4
	jmp __trap_entry
vector5:
	push 0
	push 5
	jmp __trap_entry
vector6:
	push 0
	push 6
	jmp __trap_entry
vector7:
	push 0
	push 7
	jmp __trap_entry
vector8:
	push 8
	jmp __trap_entry
vector9:
	push 0
	push 9
	jmp __trap_entry
vector10:
	push 10
	jmp __trap_entry
vector11:
	push 11
	jmp __trap_entry
vector12:
	push 12
	jmp __trap_entry
vector13:
	push 13
	jmp __trap_entry
vector14:
	push 14
	jmp __trap_entry
vector15:
	push 0
	push 15
	jmp __trap_entry
vector16:
	push 0
	push 16
	jmp __trap_entry
vector17:
	push 17
	jmp __trap_entry
vector18:
	push 0
	push 18
	jmp __trap_entry
vector19:
	push 0
	push 19
	jmp __trap_entry
vector20:
	push 0
	push 20
	jmp __trap_entry
vector21:
	push 0
	push 21
	jmp __trap_entry
vector22:
	push 0
	push 22
	jmp __trap_entry
vector23:
	push 0
	push 23
	jmp __trap_entry
vector24:
	push 0
	push 24
	jmp __trap_entry
vector25:
	push 0
	push 25
	jmp __trap_entry
vector26:
	push 0
	push 26
	jmp __trap_entry
vector27:
	push 0
	push 27
	jmp __trap_entry
vector28:
	push 0
	push 28
	jmp __trap_entry
vector29:
	push 0
	push 29
	jmp __trap_entry
vector30:
	push 0
	push 30
	jmp __trap_entry
vector31:
	push 0
	push 31
	jmp __trap_entry
vector32:
	push 0
	push 32
	jmp __trap_entry
vector33:
	push 0
	push 33
	jmp __trap_entry
vector34:
	push 0
	push 34
	jmp __trap_entry
vector35:
	push 0
	push 35
	jmp __trap_entry
vector36:
	push 0
	push 36
	jmp __trap_entry
vector37:
	push 0
	push 37
	jmp __trap_entry
vector38:
	push 0
	push 38
	jmp __trap_entry
vector39:
	push 0
	push 39
	jmp __trap_entry
vector40:
	push 0
	push 40
	jmp __trap_entry
vector41:
	push 0
	push 41
	jmp __trap_entry
vector42:
	push 0
	push 42
	jmp __trap_entry
vector43:
	push 0
	push 43
	jmp __trap_entry
vector44:
	push 0
	push 44
	jmp __trap_entry
vector45:
	push 0
	push 45
	jmp __trap_entry
vector46:
	push 0
	push 46
	jmp __trap_entry
vector47:
	push 0
	push 47
	jmp __trap_entry
vector48:
	push 0
	push 48
	jmp __trap_entry
vector49:
	push 0
	push 49
	jmp __trap_entry
vector50:
	push 0
	push 50
	jmp __trap_entry
vector51:
	push 0
	push 51
	jmp __trap_entry
vector52:
	push 0
	push 52
	jmp __trap_entry
vector53:
	push 0
	push 53
	jmp __trap_entry
vector54:
	push 0
	push 54
	jmp __trap_entry
vector55:
	push 0
	push 55
	jmp __trap_entry
vector56:
	push 0
	push 56
	jmp __trap_entry
vector57:
	push 0
	push 57
	jmp __trap_entry
vector58:
	push 0
	push 58
	jmp __trap_entry
vector59:
	push 0
	push 59
	jmp __trap_entry
vector60:
	push 0
	push 60
	jmp __trap_entry
vector61:
	push 0
	push 61
	jmp __trap_entry
vector62:
	push 0
	push 62
	jmp __trap_entry
vector63:
	push 0
	push 63
	jmp __trap_entry
vector64:
	push 0
	push 64
	jmp __trap_entry
vector65:
	push 0
	push 65
	jmp __trap_entry
vector66:
	push 0
	push 66
	jmp __trap_entry
vector67:
	push 0
	push 67
	jmp __trap_entry
vector68:
	push 0
	push 68
	jmp __trap_entry
vector69:
	push 0
	push 69
	jmp __trap_entry
vector70:
	push 0
	push 70
	jmp __trap_entry
vector71:
	push 0
	push 71
	jmp __trap_entry
vector72:
	push 0
	push 72
	jmp __trap_entry
vector73:
	push 0
	push 73
	jmp __trap_entry
vector74:
	push 0
	push 74
	jmp __trap_entry
vector75:
	push 0
	push 75
	jmp __trap_entry
vector76:
	push 0
	push 76
	jmp __trap_entry
vector77:
	push 0
	push 77
	jmp __trap_entry
vector78:
	push 0
	push 78
	jmp __trap_entry
vector79:
	push 0
	push 79
	jmp __trap_entry
vector80:
	push 0
	push 80
	jmp __trap_entry
vector81:
	push 0
	push 81
	jmp __trap_entry
vector82:
	push 0
	push 82
	jmp __trap_entry
vector83:
	push 0
	push 83
	jmp __trap_entry
vector84:
	push 0
	push 84
	jmp __trap_entry
vector85:
	push 0
	push 85
	jmp __trap_entry
vector86:
	push 0
	push 86
	jmp __trap_entry
vector87:
	push 0
	push 87
	jmp __trap_entry
vector88:
	push 0
	push 88
	jmp __trap_entry
vector89:
	push 0
	push 89
	jmp __trap_entry
vector90:
	push 0
	push 90
	jmp __trap_entry
vector91:
	push 0
	push 91
	jmp __trap_entry
vector92:
	push 0
	push 92
	jmp __trap_entry
vector93:
	push 0
	push 93
	jmp __trap_entry
vector94:
	push 0
	push 94
	jmp __trap_entry
vector95:
	push 0
	push 95
	jmp __trap_entry
vector96:
	push 0
	push 96
	jmp __trap_entry
vector97:
	push 0
	push 97
	jmp __trap_entry
vector98:
	push 0
	push 98
	jmp __trap_entry
vector99:
	push 0
	push 99
	jmp __trap_entry
vector100:
	push 0
	push 100
	jmp __trap_entry
vector101:
	push 0
	push 101
	jmp __trap_entry
vector102:
	push 0
	push 102
	jmp __trap_entry
vector103:
	push 0
	push 103
	jmp __trap_entry
vector104:
	push 0
	push 104
	jmp __trap_entry
vector105:
	push 0
	push 105
	jmp __trap_entry
vector106:
	push 0
	push 106
	jmp __trap_entry
vector107:
	push 0
	push 107
	jmp __trap_entry
vector108:
	push 0
	push 108
	jmp __trap_entry
vector109:
	push 0
	push 109
	jmp __trap_entry
vector110:
	push 0
	push 110
	jmp __trap_entry
vector111:
	push 0
	push 111
	jmp __trap_entry
vector112:
	push 0
	push 112
	jmp __trap_entry
vector113:
	push 0
	push 113
	jmp __trap_entry
vector114:
	push 0
	push 114
	jmp __trap_entry
vector115:
	push 0
	push 115
	jmp __trap_entry
vector116:
	push 0
	push 116
	jmp __trap_entry
vector117:
	push 0
	push 117
	jmp __trap_entry
vector118:
	push 0
	push 118
	jmp __trap_entry
vector119:
	push 0
	push 119
	jmp __trap_entry
vector120:
	push 0
	push 120
	jmp __trap_entry
vector121:
	push 0
	push 121
	jmp __trap_entry
vector122:
	push 0
	push 122
	jmp __trap_entry
vector123:
	push 0
	push 123
	jmp __trap_entry
vector124:
	push 0
	push 124
	jmp __trap_entry
vector125:
	push 0
	push 125
	jmp __trap_entry
vector126:
	push 0
	push 126
	jmp __trap_entry
vector127:
	push 0
	push 127
	jmp __trap_entry
vector128:
	push 0
	push 128
	jmp __trap_entry
vector129:
	push 0
	push 129
	jmp __trap_entry
vector130:
	push 0
	push 130
	jmp __trap_entry
vector131:
	push 0
	push 131
	jmp __trap_entry
vector132:
	push 0
	push 132
	jmp __trap_entry
vector133:
	push 0
	push 133
	jmp __trap_entry
vector134:
	push 0
	push 134
	jmp __trap_entry
vector135:
	push 0
	push 135
	jmp __trap_entry
vector136:
	push 0
	push 136
	jmp __trap_entry
vector137:
	push 0
	push 137
	jmp __trap_entry
vector138:
	push 0
	push 138
	jmp __trap_entry
vector139:
	push 0
	push 139
	jmp __trap_entry
vector140:
	push 0
	push 140
	jmp __trap_entry
vector141:
	push 0
	push 141
	jmp __trap_entry
vector142:
	push 0
	push 142
	jmp __trap_entry
vector143:
	push 0
	push 143
	jmp __trap_entry
vector144:
	push 0
	push 144
	jmp __trap_entry
vector145:
	push 0
	push 145
	jmp __trap_entry
vector146:
	push 0
	push 146
	jmp __trap_entry
vector147:
	push 0
	push 147
	jmp __trap_entry
vector148:
	push 0
	push 148
	jmp __trap_entry
vector149:
	push 0
	push 149
	jmp __trap_entry
vector150:
	push 0
	push 150
	jmp __trap_entry
vector151:
	push 0
	push 151
	jmp __trap_entry
vector152:
	push 0
	push 152
	jmp __trap_entry
vector153:
	push 0
	push 153
	jmp __trap_entry
vector154:
	push 0
	push 154
	jmp __trap_entry
vector155:
	push 0
	push 155
	jmp __trap_entry
vector156:
	push 0
	push 156
	jmp __trap_entry
vector157:
	push 0
	push 157
	jmp __trap_entry
vector158:
	push 0
	push 158
	jmp __trap_entry
vector159:
	push 0
	push 159
	jmp __trap_entry
vector160:
	push 0
	push 160
	jmp __trap_entry
vector161:
	push 0
	push 161
	jmp __trap_entry
vector162:
	push 0
	push 162
	jmp __trap_entry
vector163:
	push 0
	push 163
	jmp __trap_entry
vector164:
	push 0
	push 164
	jmp __trap_entry
vector165:
	push 0
	push 165
	jmp __trap_entry
vector166:
	push 0
	push 166
	jmp __trap_entry
vector167:
	push 0
	push 167
	jmp __trap_entry
vector168:
	push 0
	push 168
	jmp __trap_entry
vector169:
	push 0
	push 169
	jmp __trap_entry
vector170:
	push 0
	push 170
	jmp __trap_entry
vector171:
	push 0
	push 171
	jmp __trap_entry
vector172:
	push 0
	push 172
	jmp __trap_entry
vector173:
	push 0
	push 173
	jmp __trap_entry
vector174:
	push 0
	push 174
	jmp __trap_entry
vector175:
	push 0
	push 175
	jmp __trap_entry
vector176:
	push 0
	push 176
	jmp __trap_entry
vector177:
	push 0
	push 177
	jmp __trap_entry
vector178:
	push 0
	push 178
	jmp __trap_entry
vector179:
	push 0
	push 179
	jmp __trap_entry
vector180:
	push 0
	push 180
	jmp __trap_entry
vector181:
	push 0
	push 181
	jmp __trap_entry
vector182:
	push 0
	push 182
	jmp __trap_entry
vector183:
	push 0
	push 183
	jmp __trap_entry
vector184:
	push 0
	push 184
	jmp __trap_entry
vector185:
	push 0
	push 185
	jmp __trap_entry
vector186:
	push 0
	push 186
	jmp __trap_entry
vector187:
	push 0
	push 187
	jmp __trap_entry
vector188:
	push 0
	push 188
	jmp __trap_entry
vector189:
	push 0
	push 189
	jmp __trap_entry
vector190:
	push 0
	push 190
	jmp __trap_entry
vector191:
	push 0
	push 191
	jmp __trap_entry
vector192:
	push 0
	push 192
	jmp __trap_entry
vector193:
	push 0
	push 193
	jmp __trap_entry
vector194:
	push 0
	push 194
	jmp __trap_entry
vector195:
	push 0
	push 195
	jmp __trap_entry
vector196:
	push 0
	push 196
	jmp __trap_entry
vector197:
	push 0
	push 197
	jmp __trap_entry
vector198:
	push 0
	push 198
	jmp __trap_entry
vector199:
	push 0
	push 199
	jmp __trap_entry
vector200:
	push 0
	push 200
	jmp __trap_entry
vector201:
	push 0
	push 201
	jmp __trap_entry
vector202:
	push 0
	push 202
	jmp __trap_entry
vector203:
	push 0
	push 203
	jmp __trap_entry
vector204:
	push 0
	push 204
	jmp __trap_entry
vector205:
	push 0
	push 205
	jmp __trap_entry
vector206:
	push 0
	push 206
	jmp __trap_entry
vector207:
	push 0
	push 207
	jmp __trap_entry
vector208:
	push 0
	push 208
	jmp __trap_entry
vector209:
	push 0
	push 209
	jmp __trap_entry
vector210:
	push 0
	push 210
	jmp __trap_entry
vector211:
	push 0
	push 211
	jmp __trap_entry
vector212:
	push 0
	push 212
	jmp __trap_entry
vector213:
	push 0
	push 213
	jmp __trap_entry
vector214:
	push 0
	push 214
	jmp __trap_entry
vector215:
	push 0
	push 215
	jmp __trap_entry
vector216:
	push 0
	push 216
	jmp __trap_entry
vector217:
	push 0
	push 217
	jmp __trap_entry
vector218:
	push 0
	push 218
	jmp __trap_entry
vector219:
	push 0
	push 219
	jmp __trap_entry
vector220:
	push 0
	push 220
	jmp __trap_entry
vector221:
	push 0
	push 221
	jmp __trap_entry
vector222:
	push 0
	push 222
	jmp __trap_entry
vector223:
	push 0
	push 223
	jmp __trap_entry
vector224:
	push 0
	push 224
	jmp __trap_entry
vector225:
	push 0
	push 225
	jmp __trap_entry
vector226:
	push 0
	push 226
	jmp __trap_entry
vector227:
	push 0
	push 227
	jmp __trap_entry
vector228:
	push 0
	push 228
	jmp __trap_entry
vector229:
	push 0
	push 229
	jmp __trap_entry
vector230:
	push 0
	push 230
	jmp __trap_entry
vector231:
	push 0
	push 231
	jmp __trap_entry
vector232:
	push 0
	push 232
	jmp __trap_entry
vector233:
	push 0
	push 233
	jmp __trap_entry
vector234:
	push 0
	push 234
	jmp __trap_entry
vector235:
	push 0
	push 235
	jmp __trap_entry
vector236:
	push 0
	push 236
	jmp __trap_entry
vector237:
	push 0
	push 237
	jmp __trap_entry
vector238:
	push 0
	push 238
	jmp __trap_entry
vector239:
	push 0
	push 239
	jmp __trap_entry
vector240:
	push 0
	push 240
	jmp __trap_entry
vector241:
	push 0
	push 241
	jmp __trap_entry
vector242:
	push 0
	push 242
	jmp __trap_entry
vector243:
	push 0
	push 243
	jmp __trap_entry
vector244:
	push 0
	push 244
	jmp __trap_entry
vector245:
	push 0
	push 245
	jmp __trap_entry
vector246:
	push 0
	push 246
	jmp __trap_entry
vector247:
	push 0
	push 247
	jmp __trap_entry
vector248:
	push 0
	push 248
	jmp __trap_entry
vector249:
	push 0
	push 249
	jmp __trap_entry
vector250:
	push 0
	push 250
	jmp __trap_entry
vector251:
	push 0
	push 251
	jmp __trap_entry
vector252:
	push 0
	push 252
	jmp __trap_entry
vector253:
	push 0
	push 253
	jmp __trap_entry
vector254:
	push 0
	push 254
	jmp __trap_entry
vector255:
	push 0
	push 255
	jmp __trap_entry

.section .rodata
.global __vectors
__vectors:
	.quad vector0
	.quad vector1
	.quad vector2
	.quad vector3
	.quad vector4
	.quad vector5
	.quad vector6
	.quad vector7
	.quad vector8
	.quad vector9
	.quad vector10
	.quad vector11
	.quad vector12
	.quad vector13
	.quad vector14
	.quad vector15
	.quad vector16
	.quad vector17
	.quad vector18
	.quad vector19
	.quad vector20
	.quad vector21
	.quad vector22
	.quad vector23
	.quad vector24
	.quad vector25
	.quad vector26
	.quad vector27
	.quad vector28
	.quad vector29
	.quad vector30
	.quad vector31
	.quad vector32
	.quad vector33
	.quad vector34
	.quad vector35
	.quad vector36
	.quad vector37
	.quad vector38
	.quad vector39
	.quad vector40
	.quad vector41
	.quad vector42
	.quad vector43
	.quad vector44
	.quad vector45
	.quad vector46
	.quad vector47
	.quad vector48
	.quad vector49
	.quad vector50
	.quad vector51
	.quad vector52
	.quad vector53
	.quad vector54
	.quad vector55
	.quad vector56
	.quad vector57
	.quad vector58
	.quad vector59
	.quad vector60
	.quad vector61
	.quad vector62
	.quad vector63
	.quad vector64
	.quad vector65
	.quad vector66
	.quad vector67
	.quad vector68
	.quad vector69
	.quad vector70
	.quad vector71
	.quad vector72
	.quad vector73
	.quad vector74
	.quad vector75
	.quad vector76
	.quad vector77
	.quad vector78
	.quad vector79
	.quad vector80
	.quad vector81
	.quad vector82
	.quad vector83
	.quad vector84
	.quad vector85
	.quad vector86
	.quad vector87
	.quad vector88
	.quad vector89
	.quad vector90
	.quad vector91
	.quad vector92
	.quad vector93
	.quad vector94
	.quad vector95
	.quad vector96
	.quad vector97
	.quad vector98
	.quad vector99
	.quad vector100
	.quad vector101
	.quad vector102
	.quad vector103
	.quad vector104
	.quad vector105
	.quad vector106
	.quad vector107
	.quad vector108
	.quad vector109
	.quad vector110
	.quad vector111
	.quad vector112
	.quad vector113
	.quad vector114
	.quad vector115
	.quad vector116
	.quad vector117
	.quad vector118
	.quad vector119
	.quad vector120
	.quad vector121
	.quad vector122
	.quad vector123
	.quad vector124
	.quad vector125
	.quad vector126
	.quad vector127
	.quad vector128
	.quad vector129
	.quad vector130
	.quad vector131
	.quad vector132
	.quad vector133
	.quad vector134
	.quad vector135
	.quad vector136
	.quad vector137
	.quad vector138
	.quad vector139
	.quad vector140
	.quad vector141
	.quad vector142
	.quad vector143
	.quad vector144
	.quad vector145
	.quad vector146
	.quad vector147
	.quad vector148
	.quad vector149
	.quad vector150
	.quad vector151
	.quad vector152
	.quad vector153
	.quad vector154
	.quad vector155
	.quad vector156
	.quad vector157
	.quad vector158
	.quad vector159
	.quad vector160
	.quad vector161
	.quad vector162
	.quad vector163
	.quad vector164
	.quad vector165
	.quad vector166
	.quad vector167
	.quad vector168
	.quad vector169
	.quad vector170
	.quad vector171
	.quad vector172
	.quad vector173
	.quad vector174
	.quad vector175
	.quad vector176
	.quad vector177
	.quad vector178
	.quad vector179
	.quad vector180
	.quad vector181
	.quad vector182
	.quad vector183
	.quad vector184
	.quad vector185
	.quad vector186
	.quad vector187
	.quad vector188
	.quad vector189
	.quad vector190
	.quad vector191
	.quad vector192
	.quad vector193
	.quad vector194
	.quad vector195
	.quad vector196
	.quad vector197
	.quad vector198
	.quad vector199
	.quad vector200
	.quad vector201
	.quad vector202
	.quad vector203
	.quad vector204
	.quad vector205
	.quad vector206
	.quad vector207
	.quad vector208
	.quad vector209
	.quad vector210
	.quad vector211
	.quad vector212
	.quad vector213
	.quad vector214
	.quad vector215
	.quad vector216
	.quad vector217
	.quad vector218
	.quad vector219
	.quad vector220
	.quad vector221
	.quad vector222
	.quad vector223
	.quad vector224
	.quad vector225
	.quad vector226
	.quad vector227
	.quad vector228
	.quad vector229
	.quad vector230
	.quad vector231
	.quad vector232
	.quad vector233
	.quad vector234
	.quad vector235
	.quad vector236
	.quad vector237
	.quad vector238
	.quad vector239
	.quad vector240
	.quad vector241
	.quad vector242
	.quad vector243
	.quad vector244
	.quad vector245
	.quad vector246
	.quad vector247
	.quad vector248
	.quad vector249
	.quad vector250
	.quad vector251
	.quad vector252
	.quad vector253
	.quad vector254
	.quad vector255
