[package]
name = "jinux-pci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
spin = "0.9.4"
jinux-frame = { path = "../../../framework/jinux-frame" }
jinux-util = { path = "../../libs/jinux-util" }
pod = { git = "https://github.com/jinzhao-dev/pod", rev = "7fa2ed2" }
component = { path = "../../libs/comp-sys/component" }
log = "0.4"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[features]
