# This file (`.github/mergeable.yml`) is the configuration of the mergeable bot:
# https://github.com/apps/mergeable

version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: commit
        message:
          regex: ^.*(@antgroup\.com|@alibaba-inc\.com|@intel\.com)$
          message: Check if the author emails belong to Ant Group or its partners
          message_type: author_email
          skip_merge: false # If true, will skip commit with message that includes 'Merge'
          oldest_only: false
          newest_only: false
          single_commit_only: false # If true, will only process this validator if there is one commit
    pass:
      - do: checks
        status: 'success'
