# This file (`.github/mergeable.yml`) is the configuration of the mergeable bot:
# https://github.com/apps/mergeable

version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: commit
        message:
          # `akucxy@163.com` belongs to `@Js2xxx`, who has not yet obtained his PKU email.
          regex: ^((.*(@antgroup\.com|@alibaba-inc\.com|@intel\.com|@pku\.edu\.cn|@stu\.pku\.edu\.cn|@zgclab\.edu\.cn|@mail\.zgclab\.edu\.cn))|akucxy@163\.com)$
          message: Check if the author emails belong to Ant Group or its partners
          message_type: author_email
          skip_merge: false # If true, will skip commit with message that includes 'Merge'
          oldest_only: false
          newest_only: false
          single_commit_only: false # If true, will only process this validator if there is one commit
    pass:
      - do: checks
        status: 'success'
