// SPDX-License-Identifier: MPL-2.0

//! A set of the kernel command line parameters to be handled early on by OSTD.
//!
//! Most parameters are recognized and handled by the Asterinas kernel,
//! but a few must be done early on by OSTD.
//! For example,
//! `earlycon` specifies why an early console (most commonly based on UART) should be initialized.
//! The early console is the only viable sink for log messages
//! generated by OSTD in the early stage,
//! before it handles the control of CPU to the Asterinas kernel.
//!
//! OSTD allows injecting a parser for these early command line parameters
//! via [`ostd::early_cmdline_parser`].
//! The injected parser is invoked so early
//! even the heap allocator is not ready.
//! As such, all parser logic in this module has to be written as const expressions.

use ostd::{boot::EarlyCmdline, log::LevelFilter};

/// Kernel command-line keys consumed by [`early_cmdline_parser`].
///
/// These are stripped during dispatch so they are not forwarded to init.
const EARLY_PARAMS: &[&str] = &["earlycon", "loglevel"];

/// Returns whether `normalized_key` is handled only by the early parser.
pub(super) fn is_early_param(normalized_key: &str) -> bool {
    EARLY_PARAMS.contains(&normalized_key)
}

/// Registers the kernel's early command-line parser with OSTD.
///
/// Scans space-separated tokens in `cmdline` and returns [`EarlyCmdline`] for
/// OSTD to configure the early serial console and log filter.
///
/// # Recognized tokens
///
/// - `earlycon` — enables the early UART console (exact token match).
/// - `loglevel=N` — sets the OSTD log filter (`N` in `0..=8`, see [`LevelFilter`]).
/// - `loglevel=LEVEL` — also accepts textual levels such as `error` or `debug`.
/// - `--` — stops parsing; all following tokens are for the init process.
///
/// Double quotes (`"`) protect spaces inside one token (Linux-compatible).
/// Other tokens are ignored. When `loglevel` is absent, the default is `8`
/// ([`LevelFilter::Debug`]). When `earlycon` is absent, the early console stays disabled.
#[ostd::early_cmdline_parser]
const fn early_cmdline_parser(cmdline: &str) -> EarlyCmdline {
    let mut has_early_console = false;
    let mut log_level = LevelFilter::Debug;

    let bytes: &[u8] = cmdline.as_bytes();
    let mut index = 0;
    while index < bytes.len() {
        // Skip leading separators before scanning the next token.
        while index < bytes.len() && bytes[index].is_ascii_whitespace() {
            index += 1;
        }
        if index >= bytes.len() {
            break;
        }

        let start: usize = index;
        let mut inside_quotes = false;
        // Linux-style tokenization: whitespace splits only outside double quotes.
        while index < bytes.len() {
            let byte = bytes[index];
            if byte == b'"' {
                inside_quotes = !inside_quotes;
            } else if byte.is_ascii_whitespace() && !inside_quotes {
                break;
            }
            index += 1;
        }

        let (token_start, token_end) = strip_linux_double_quotes(bytes, start, index);

        // Only early-only keys are consumed here; other tokens are ignored.
        if match_token(bytes, token_start, token_end, b"--") {
            // `--` terminates kernel-side parsing; remaining tokens belong to init.
            break;
        } else if match_token(bytes, token_start, token_end, b"earlycon") {
            has_early_console = true;
        } else if starts_with_at(bytes, token_start, token_end, b"loglevel=")
            && let Some(parsed_log_level) = parse_loglevel_at(bytes, token_start + 9, token_end)
        {
            log_level = parsed_log_level;
        }
    }

    EarlyCmdline {
        log_level,
        has_early_console,
    }
}

/// Strips Linux-style surrounding quotes from a token or value.
const fn strip_linux_double_quotes(bytes: &[u8], start: usize, end: usize) -> (usize, usize) {
    if start < end && bytes[start] == b'"' {
        let new_start = start + 1;
        if new_start < end && bytes[end - 1] == b'"' {
            (new_start, end - 1)
        } else {
            (new_start, end)
        }
    } else {
        (start, end)
    }
}

/// Parses a `loglevel` value from `bytes[start..end]`.
///
/// Accepts `0..=8` or lowercase level names. Returns `None` for malformed values
/// so they do not override earlier valid settings.
const fn parse_loglevel_at(bytes: &[u8], start: usize, end: usize) -> Option<LevelFilter> {
    let (mut start, value_end) = strip_linux_double_quotes(bytes, start, end);

    if start >= value_end {
        return None;
    }

    if bytes[start].is_ascii_digit() {
        let mut result: u8 = 0;
        while start < value_end {
            let byte = bytes[start];
            if !byte.is_ascii_digit() {
                return None;
            }
            let digit = byte - b'0';
            result = result.saturating_mul(10).saturating_add(digit);
            start += 1;
        }

        if result > 8 {
            return None;
        }
        return Some(LevelFilter::from_u8(result));
    }

    parse_loglevel_name_at(bytes, start, value_end)
}

/// Parses lowercase textual loglevel names.
const fn parse_loglevel_name_at(bytes: &[u8], start: usize, end: usize) -> Option<LevelFilter> {
    if match_token(bytes, start, end, b"off") {
        Some(LevelFilter::Off)
    } else if match_token(bytes, start, end, b"emerg") {
        Some(LevelFilter::Emerg)
    } else if match_token(bytes, start, end, b"alert") {
        Some(LevelFilter::Alert)
    } else if match_token(bytes, start, end, b"crit") {
        Some(LevelFilter::Crit)
    } else if match_token(bytes, start, end, b"error") || match_token(bytes, start, end, b"err") {
        Some(LevelFilter::Error)
    } else if match_token(bytes, start, end, b"warning") || match_token(bytes, start, end, b"warn")
    {
        Some(LevelFilter::Warning)
    } else if match_token(bytes, start, end, b"notice") {
        Some(LevelFilter::Notice)
    } else if match_token(bytes, start, end, b"info") {
        Some(LevelFilter::Info)
    } else if match_token(bytes, start, end, b"debug") {
        Some(LevelFilter::Debug)
    } else {
        None
    }
}

/// Returns whether `bytes[start..end]` equals `target`.
const fn match_token(bytes: &[u8], start: usize, end: usize, target: &[u8]) -> bool {
    if end - start != target.len() {
        return false;
    }
    starts_with_at(bytes, start, end, target)
}

/// Returns whether `bytes[start..end]` starts with `prefix`.
const fn starts_with_at(bytes: &[u8], start: usize, end: usize, prefix: &[u8]) -> bool {
    if end - start < prefix.len() {
        return false;
    }
    let mut index = 0;
    while index < prefix.len() {
        if bytes[start + index] != prefix[index] {
            return false;
        }
        index += 1;
    }
    true
}

#[cfg(ktest)]
mod tests {
    use ostd::prelude::*;

    use super::*;

    #[ktest]
    fn is_early_param_recognizes_early_keys() {
        assert!(is_early_param("earlycon"));
        assert!(is_early_param("loglevel"));
        assert!(!is_early_param("log_level"));
        assert!(!is_early_param("unknown"));
    }

    #[ktest]
    fn early_cmdline_parser_defaults() {
        let result = early_cmdline_parser("");
        assert_eq!(result.log_level, LevelFilter::Debug);
        assert!(!result.has_early_console);
    }

    #[ktest]
    fn early_cmdline_parser_earlycon() {
        assert!(early_cmdline_parser("earlycon").has_early_console);
        assert!(early_cmdline_parser("\"earlycon\"").has_early_console);
        assert!(!early_cmdline_parser("\"  earlycon \"").has_early_console);
        assert!(!early_cmdline_parser("earlyconxxxx").has_early_console);
    }

    #[ktest]
    fn early_cmdline_parser_loglevel() {
        assert_eq!(
            early_cmdline_parser("loglevel=0").log_level,
            LevelFilter::Off
        );
        assert_eq!(
            early_cmdline_parser("loglevel=\"0\"").log_level,
            LevelFilter::Off
        );
        assert_eq!(
            early_cmdline_parser("\"loglevel=0\"").log_level,
            LevelFilter::Off
        );
        assert_eq!(
            early_cmdline_parser("loglevel=4").log_level,
            LevelFilter::Error
        );
        assert_eq!(
            early_cmdline_parser("loglevel=3x").log_level,
            LevelFilter::Debug
        );
        assert_eq!(
            early_cmdline_parser("loglevel=9").log_level,
            LevelFilter::Debug
        );
        assert_eq!(
            early_cmdline_parser("loglevel=error").log_level,
            LevelFilter::Error
        );
        assert_eq!(
            early_cmdline_parser("loglevel=ERR").log_level,
            LevelFilter::Debug
        );
        assert_eq!(
            early_cmdline_parser("loglevel=warn").log_level,
            LevelFilter::Warning
        );
        assert_eq!(
            early_cmdline_parser("loglevel=\"info\"").log_level,
            LevelFilter::Info
        );
    }

    #[ktest]
    fn early_cmdline_parser_last_loglevel_wins() {
        assert_eq!(
            early_cmdline_parser("loglevel=4 loglevel=0").log_level,
            LevelFilter::Off
        );
    }

    #[ktest]
    fn early_cmdline_parser_invalid_loglevel_does_not_override() {
        assert_eq!(
            early_cmdline_parser("loglevel=0 loglevel=3x").log_level,
            LevelFilter::Off
        );
        assert_eq!(
            early_cmdline_parser("loglevel=error loglevel=").log_level,
            LevelFilter::Error
        );
        assert_eq!(
            early_cmdline_parser("loglevel=warn loglevel=9").log_level,
            LevelFilter::Warning
        );
    }

    #[ktest]
    fn early_cmdline_parser_stops_at_double_dash() {
        let result = early_cmdline_parser("loglevel=0 -- loglevel=4 earlycon");
        assert_eq!(result.log_level, LevelFilter::Off);
        assert!(!result.has_early_console);
    }

    #[ktest]
    fn early_cmdline_parser_quotes_protect_spaces() {
        let result = early_cmdline_parser("loglevel=0 \"ignored -- token\" earlycon");
        assert_eq!(result.log_level, LevelFilter::Off);
        assert!(result.has_early_console);
    }
}
