[package]
name = "jinux-boot"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runner-utils = "0.0.2"
anyhow = "1.0.32"
cfg-if = "1.0"

[features]
default = ["limine"]
limine = []
iommu = []
