[package]
name = "jinux-frame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
cfg-if = "1.0"
spin = "0.9.4"
volatile = { version = "0.4.5", features = ["unstable"] }
buddy_system_allocator = "0.9.0"
pod = { git = "https://github.com/sdww0/POD", rev = "7fa2ed2" }
intrusive-collections = "0.9.5"
log = "0.4"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
trapframe = { git = "https://github.com/sdww0/trapframe-rs", rev = "94fc010" }

limine = { version = "0.1.10", features = ["into-uuid"], optional = true }
x86_64 = { version = "0.14.2", optional = true }
x86 = { version = "0.52.0", optional = true }
acpi = { version = "4.1.1", optional = true }

[features]
default = ["x86_64"]
x86_64 = ["dep:x86_64", "dep:x86", "dep:limine", "dep:acpi"]
