[package]
name = "kxos-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kxos-frame = {path = "../kxos-frame"}

[features]

