# SPDX-License-Identifier: MPL-2.0

SUBDIRS := \
	ext2 \
	fdatasync \
	inotify \
	group_perm \
	isolation \
	mount \
	overlayfs \
	procfs \
	pseudofs \
	symlink \
	open_dir \

include ../common/Makefile
