// SPDX-License-Identifier: MPL-2.0

//! A set of the kernel command line parameters to be handled early on by OSTD.
//!
//! Most parameters are recognized and handled by the Asterinas kernel,
//! but a few must be done early on by OSTD.
//! For example,
//! `earlycon` specifies why an early console (most commonly based on UART) should be initialized.
//! The early console is the only viable sink for log messages
//! generated by OSTD in the early stage,
//! before it handles the control of CPU to the Asterinas kernel.
//!
//! OSTD allows injecting a parser for these early command line parameters
//! via [`ostd::early_cmdline_parser`].
//! The injected parser is invoked so early
//! even the heap allocator is not ready.
//! As such, all parser logic in this module has to be written as const expressions.

use ostd::{boot::EarlyCmdline, log::LevelFilter};

/// Kernel command-line keys consumed by [`early_cmdline_parser`].
///
/// These are stripped during dispatch so they are not forwarded to init.
const EARLY_PARAMS: &[&str] = &["earlycon", "loglevel"];

/// Returns whether `key` is handled only by the early parser.
pub(super) fn is_early_param(key: &str) -> bool {
    EARLY_PARAMS.contains(&key)
}

/// Registers the kernel's early command-line parser with OSTD.
///
/// Scans space-separated tokens in `cmdline` and returns [`EarlyCmdline`] for
/// OSTD to configure the early serial console and log filter.
///
/// # Recognized tokens
///
/// - `earlycon` — enables the early UART console (exact token match).
/// - `loglevel=N` — sets the OSTD log filter (`N` in `0..=8`, see [`LevelFilter`]).
/// - `loglevel=LEVEL` — also accepts textual levels such as `error` or `debug`.
/// - `--` — stops parsing; all following tokens are for the init process.
///
/// Double quotes (`"`) protect spaces inside one token (Linux-compatible).
/// Other tokens are ignored. When `loglevel` is absent, the default is `8`
/// ([`LevelFilter::Debug`]). When `earlycon` is absent, the early console stays disabled.
#[ostd::early_cmdline_parser]
const fn early_cmdline_parser(cmdline: &str) -> EarlyCmdline {
    let mut has_early_console = false;
    let mut log_level = LevelFilter::Debug;

    let bytes: &[u8] = cmdline.as_bytes();
    let mut index = 0;
    while index < bytes.len() {
        // Skip leading separators before scanning the next token.
        while index < bytes.len() && bytes[index].is_ascii_whitespace() {
            index += 1;
        }
        if index >= bytes.len() {
            break;
        }

        let start: usize = index;
        let mut inside_quotes = false;
        // Linux-style tokenization: whitespace splits only outside double quotes.
        while index < bytes.len() {
            let byte = bytes[index];
            if byte == b'"' {
                inside_quotes = !inside_quotes;
            } else if byte.is_ascii_whitespace() && !inside_quotes {
                break;
            }
            index += 1;
        }

        let token = strip_linux_double_quotes(bytes, start, index);

        // Only early-only keys are consumed here; other tokens are ignored.
        if matches!(token, b"--") {
            // `--` terminates kernel-side parsing; remaining tokens belong to init.
            break;
        } else if matches!(token, b"earlycon") {
            has_early_console = true;
        } else if let Some((key, value)) = token.split_at_checked(9)
            && matches!(key, b"loglevel=")
            && let Some(parsed_log_level) = parse_loglevel_at(value)
        {
            log_level = parsed_log_level;
        }
    }

    EarlyCmdline {
        log_level,
        has_early_console,
    }
}

/// Strips Linux-style surrounding quotes from a token or value.
const fn strip_linux_double_quotes(bytes: &[u8], start: usize, end: usize) -> &[u8] {
    let (new_start, new_end) = if start < end && bytes[start] == b'"' {
        let new_start = start + 1;
        if new_start < end && bytes[end - 1] == b'"' {
            (new_start, end - 1)
        } else {
            (new_start, end)
        }
    } else {
        (start, end)
    };
    bytes.split_at(new_start).1.split_at(new_end - new_start).0
}

/// Parses a `loglevel` value.
///
/// Accepts `0..=8` or lowercase level names. Returns `None` for malformed values
/// so they do not override earlier valid settings.
const fn parse_loglevel_at(bytes: &[u8]) -> Option<LevelFilter> {
    let bytes = strip_linux_double_quotes(bytes, 0, bytes.len());

    if bytes.is_empty() {
        return None;
    }

    if bytes[0].is_ascii_digit() {
        if let Ok(result) = u8::from_ascii_radix(bytes, 10)
            && result <= 8
        {
            return Some(LevelFilter::from_u8(result));
        }
        return None;
    }

    parse_loglevel_name_at(bytes)
}

/// Parses lowercase textual loglevel names.
const fn parse_loglevel_name_at(bytes: &[u8]) -> Option<LevelFilter> {
    match bytes {
        b"off" => Some(LevelFilter::Off),
        b"emerg" => Some(LevelFilter::Emerg),
        b"alert" => Some(LevelFilter::Alert),
        b"crit" => Some(LevelFilter::Crit),
        b"error" | b"err" => Some(LevelFilter::Error),
        b"warning" | b"warn" => Some(LevelFilter::Warning),
        b"notice" => Some(LevelFilter::Notice),
        b"info" => Some(LevelFilter::Info),
        b"debug" => Some(LevelFilter::Debug),
        _ => None,
    }
}

#[cfg(ktest)]
mod tests {
    use ostd::prelude::*;

    use super::*;

    #[ktest]
    fn is_early_param_recognizes_early_keys() {
        assert!(is_early_param("earlycon"));
        assert!(is_early_param("loglevel"));
        assert!(!is_early_param("log_level"));
        assert!(!is_early_param("unknown"));
    }

    #[ktest]
    fn early_cmdline_parser_defaults() {
        let result = early_cmdline_parser("");
        assert_eq!(result.log_level, LevelFilter::Debug);
        assert!(!result.has_early_console);
    }

    #[ktest]
    fn early_cmdline_parser_earlycon() {
        assert!(early_cmdline_parser("earlycon").has_early_console);
        assert!(early_cmdline_parser("\"earlycon\"").has_early_console);
        assert!(!early_cmdline_parser("\"  earlycon \"").has_early_console);
        assert!(!early_cmdline_parser("earlyconxxxx").has_early_console);
    }

    #[ktest]
    fn early_cmdline_parser_loglevel() {
        assert_eq!(
            early_cmdline_parser("loglevel=0").log_level,
            LevelFilter::Off
        );
        assert_eq!(
            early_cmdline_parser("loglevel=\"0\"").log_level,
            LevelFilter::Off
        );
        assert_eq!(
            early_cmdline_parser("\"loglevel=0\"").log_level,
            LevelFilter::Off
        );
        assert_eq!(
            early_cmdline_parser("loglevel=3").log_level,
            LevelFilter::Crit
        );
        assert_eq!(
            early_cmdline_parser("loglevel=3x").log_level,
            LevelFilter::Debug
        );
        assert_eq!(
            early_cmdline_parser("loglevel=9").log_level,
            LevelFilter::Debug
        );
        assert_eq!(
            early_cmdline_parser("loglevel=error").log_level,
            LevelFilter::Error
        );
        assert_eq!(
            early_cmdline_parser("loglevel=err").log_level,
            LevelFilter::Error
        );
        assert_eq!(
            early_cmdline_parser("loglevel=off").log_level,
            LevelFilter::Off
        );
        assert_eq!(
            early_cmdline_parser("loglevel=warn").log_level,
            LevelFilter::Warning
        );
        assert_eq!(
            early_cmdline_parser("loglevel=Warn").log_level,
            LevelFilter::Debug
        );
    }

    #[ktest]
    fn early_cmdline_parser_last_loglevel_wins() {
        assert_eq!(
            early_cmdline_parser("loglevel=4 loglevel=0").log_level,
            LevelFilter::Off
        );
    }

    #[ktest]
    fn early_cmdline_parser_invalid_loglevel_does_not_override() {
        assert_eq!(
            early_cmdline_parser("loglevel=0 loglevel=3x").log_level,
            LevelFilter::Off
        );
        assert_eq!(
            early_cmdline_parser("loglevel=error loglevel=").log_level,
            LevelFilter::Error
        );
        assert_eq!(
            early_cmdline_parser("loglevel=warn loglevel=9").log_level,
            LevelFilter::Warning
        );
    }

    #[ktest]
    fn early_cmdline_parser_stops_at_double_dash() {
        let result = early_cmdline_parser("loglevel=0 -- loglevel=4 earlycon");
        assert_eq!(result.log_level, LevelFilter::Off);
        assert!(!result.has_early_console);
    }

    #[ktest]
    fn early_cmdline_parser_quotes_protect_spaces() {
        let result = early_cmdline_parser("loglevel=0 \"ignored -- token\" earlycon");
        assert_eq!(result.log_level, LevelFilter::Off);
        assert!(result.has_early_console);
    }
}
