[package]
name = "jinux-block"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
spin = "0.9.4"
jinux-frame = {path = "../../../framework/jinux-frame"}
jinux-pci = {path="../pci"}
jinux-virtio = {path="../virtio"}
jinux-util = {path="../../libs/jinux-util"}
pod = {path = "../../../framework/pod"}
pod-derive = {path = "../../../framework/pod-derive"}
component = {path="../../comp-sys/component"}
log = "0.4"

[features]

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
