# SPDX-License-Identifier: MPL-2.0

SUBDIRS := \
	ext2 \
	fdatasync \
	getcwd \
	inotify \
	isolation \
	mount \
	overlayfs \
	procfs \
	pseudofs \
	statx \
	symlink \
	sync \
	tmpfile \
	utimensat \

include ../common/Makefile
