[package]
name = "aster-keyboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
component = { path = "../../libs/comp-sys/component" }
ostd = { path = "../../../ostd" }
bitflags = "2.5"
log = "0.4"
spin = "0.9.4"
aster-input = { path = "../input" }

[lints]
workspace = true
