# SPDX-License-Identifier: MPL-2.0

include ../test_common.mk

# Removed `-static` to enable dynamic linking.
# Refer to "signal_rflags_df.c" for details on how dynamic linking affects DF flag testing.
EXTRA_C_FLAGS :=
