#!/usr/bin/env bash

# SPDX-License-Identifier: MPL-2.0

# Usage: merge_nixos_config.sh <base_file> <extra_file> <merged_file>
#
# This script takes two NixOS configuration files, <base_file> and <extra_file>,
# as inputs and produces a new NixOS configuration file whose content is the
# combination of the two inputs. If the same key is set by both <base_file>
# and <extra_file>, then the value provided by <extra_file> takes precedence.
#
# NOTES: If `<extra_file>` and `<merged_file>` refer to the same file while
# `<base_file>` is different, the script rejects the invocation to avoid
# circular import.
#
# A NixOS configuration file, usually named `configuration.nix`, is written in
# the following form:
#
# { config, lib, pkgs, ... }: {
#     key1 = value1;
#     key2 = value2;
# }

set -euo pipefail

# Check for the correct number of arguments
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <base_file> <extra_file> <merged_file>"
    exit 1
fi

BASE_FILE="$1"
EXTRA_FILE="$2"
MERGED_FILE="$3"
EXTRA_DIR="$(cd "$(dirname "$EXTRA_FILE")" && pwd)"

# Check if input files exist
if [ ! -f "$BASE_FILE" ]; then
    echo "Error: Base file not found at '$BASE_FILE'"
    exit 1
fi

if [ ! -f "$EXTRA_FILE" ]; then
    echo "Error: Extra file not found at '$EXTRA_FILE'"
    exit 1
fi

ABS_BASE="$(realpath "$BASE_FILE")"
ABS_EXTRA="$(realpath "$EXTRA_FILE")"
ABS_MERGED="$(realpath -m "$MERGED_FILE")"

if [ "$ABS_BASE" = "$ABS_EXTRA" ] && [ "$ABS_EXTRA" = "$ABS_MERGED" ]; then
    exit 0
fi

if [ "$ABS_EXTRA" = "$ABS_MERGED" ]; then
    echo "Error: merged_file must not alias extra_file"
    exit 1
fi

BASE_CONTENT="$(cat "$BASE_FILE")"
EXTRA_CONTENT="$(cat "$EXTRA_FILE")"
EXTRA_DIR_NIX_STRING="$(printf '%s' "$EXTRA_DIR" | sed 's/\\/\\\\/g; s/"/\\"/g')"

cat > "$MERGED_FILE" <<EOF
# This file is generated by merge_nixos_config.sh
# It merges two configuration files. Do not edit directly.

{ config, lib, pkgs, ... }:
let
  # The extra module is embedded below, so relative paths inside it would resolve
  # against this generated file. Use this path when a test module needs assets
  # from its original test directory.
  extraFileDir = /. + "$EXTRA_DIR_NIX_STRING";

  # The content of the original modules is embedded here.
  baseModule = (
EOF

printf '%s\n' \
  "$BASE_CONTENT" \
  '  );' \
  '' \
  '  extraModule = (' \
  "$EXTRA_CONTENT" \
  '  );' \
  '' \
  '  # Evaluate each module with the standard NixOS arguments' \
  '  base = baseModule { inherit config lib pkgs; };' \
  '  extra = extraModule { inherit config lib pkgs; };' \
  'in' \
  '  # Deeply merge the base and extra configurations.' \
  '  # The value from extra_file takes precedence.' \
  '  lib.recursiveUpdate base extra' >> "$MERGED_FILE"
