// SPDX-License-Identifier: MPL-2.0

use alloc::{
    boxed::Box,
    collections::BinaryHeap,
    sync::{Arc, Weak},
    vec::Vec,
};
use core::time::Duration;

use aster_frame::{arch::register_interrupt_callback, sync::SpinLock};

use super::{clock::Clock, timer_callback::TimerCallback};

/// A timer with periodic functionality.
///
/// Setting the timer will trigger a callback function upon expiration of
/// the set time. If the timer has a interval time set, it will use
/// the interval time to configure a new timing after expiration.
pub struct IntervalTimer {
    interval: SpinLock<Duration>,
    timer_manager: TimerManager,
    callback_function: Box<dyn Fn() + Send + Sync>,
    timer_callback: SpinLock<Weak<TimerCallback>>,
}

impl IntervalTimer {
    /// Create a `IntervalTimer` instance from a `TimerManager`.
    /// The generated `TimerCallback` of this timer will be managed by the `TimerManager`.
    pub fn new<F>(callback_function: F, timer_manager: TimerManager) -> Arc<Self>
    where
        F: Fn() + Send + Sync + 'static,
    {
        Arc::new(Self {
            interval: SpinLock::new(Duration::ZERO),
            timer_manager,
            callback_function: Box::new(callback_function),
            timer_callback: SpinLock::new(Weak::default()),
        })
    }

    /// Set the interval time for this timer.
    /// The timer will be reset with the interval time upon expiration.
    pub fn set_interval(&self, interval: Duration) {
        *self.interval.lock_irq_disabled() = interval;
    }

    /// Clear the `TimerCallback` generated by this timer.
    pub fn clear(&self) {
        let timer_callback = self.timer_callback.lock_irq_disabled();
        if let Some(timer_callback) = timer_callback.upgrade() {
            timer_callback.cancel();
        }
    }

    /// Set the timer with a timeout.
    ///
    /// It will generate a `TimerCallback`, which will generally execute the callback
    /// function when reaching timeout.
    pub fn set_timer(self: &Arc<Self>, timeout: Duration) {
        let now = self.timer_manager.clock().read_time();
        let expired_time = now + timeout;
        let timer = self.clone();
        let new_timer_callback = Arc::new(TimerCallback::new(
            expired_time,
            Box::new(move || interval_timer_callback(&timer)),
        ));

        let mut timer_callback = self.timer_callback.lock_irq_disabled();
        if let Some(timer_callback) = timer_callback.upgrade() {
            timer_callback.cancel();
        }
        self.timer_manager.insert(new_timer_callback.clone());
        *timer_callback = Arc::downgrade(&new_timer_callback);
    }

    /// Return the current expired time of this timer.
    pub fn expired_time(&self) -> Duration {
        let timer_callback = self.timer_callback.lock_irq_disabled().upgrade();
        timer_callback.map_or(Duration::ZERO, |timer_callback| {
            timer_callback.expire_time()
        })
    }

    /// Return the remain time to expiration of this timer.
    pub fn remain(&self) -> Duration {
        let now = self.timer_manager.clock().read_time();
        let expired_time = self.expired_time();
        if expired_time > now {
            expired_time - now
        } else {
            Duration::ZERO
        }
    }
}

fn interval_timer_callback(timer: &Arc<IntervalTimer>) {
    (timer.callback_function)();
    let interval = timer.interval.lock_irq_disabled();
    if *interval != Duration::ZERO {
        timer.set_timer(*interval);
    }
}

/// The TimerManager is used to manage a Clock and TimerCallbacks set
/// based on that Clock. Users utilize the corresponding Clock's features
/// through the TimerManager, and can also create timers based on
/// that Clock with the TimerManager.
#[derive(Clone)]
pub struct TimerManager {
    clock: Arc<dyn Clock>,
    timer_callbacks: Arc<SpinLock<BinaryHeap<Arc<TimerCallback>>>>,
}

impl TimerManager {
    /// Create a `TimerManager` Instance from a clock.
    pub fn new(clock: Arc<dyn Clock>) -> Self {
        Self {
            clock,
            timer_callbacks: Arc::new(SpinLock::new(BinaryHeap::new())),
        }
    }

    /// Insert a `TimerCallback` to this `TimerManager`.
    pub fn insert(&self, timer_callback: Arc<TimerCallback>) {
        self.timer_callbacks
            .lock_irq_disabled()
            .push(timer_callback);
    }

    fn clock(&self) -> &Arc<dyn Clock> {
        &self.clock
    }

    /// Set this `TimerManager` global, which means the system will check and call
    /// the expired `TimerCallback`s in this manager during the system timer interruption.
    pub fn set_global(&self) {
        let manager_clone = self.clone();
        let callback = move || {
            manager_clone.call_expired_timer();
        };
        register_interrupt_callback(Box::new(callback));
    }

    /// Check the managed `TimerCallback`s, and if any have timed out,
    /// call the corresponding callback functions.
    pub fn call_expired_timer(&self) {
        let callbacks = {
            let mut timeout_list = self.timer_callbacks.lock_irq_disabled();
            if timeout_list.len() == 0 {
                return;
            }

            let mut callbacks = Vec::new();
            let current_time = self.clock().read_time();
            while let Some(t) = timeout_list.peek() {
                if t.is_cancelled() {
                    // Just ignore the cancelled callback
                    timeout_list.pop();
                } else if t.is_expired(current_time) {
                    callbacks.push(timeout_list.pop().unwrap());
                } else {
                    break;
                }
            }
            callbacks
        };

        for callback in callbacks {
            callback.callback();
        }
    }

    /// Create a `IntervalTimer`, whose generated `TimerCallback` will be
    /// managed by this `TimerManager`.
    pub fn create_timer<F>(&self, function: F) -> Arc<IntervalTimer>
    where
        F: Fn() + Send + Sync + 'static,
    {
        IntervalTimer::new(function, self.clone())
    }
}
