#!/bin/bash

# SPDX-License-Identifier: MPL-2.0

set -euo pipefail

daemon_bin=/usr/libexec/virtiofsd
work_dir=/tmp/asterinas-virtiofs
cache_mode=auto

usage() {
    cat <<'EOF'
Usage: run_virtiofsd.sh [OPTIONS]

Run virtiofsd with paths rooted under the work directory.

Options:
  --daemon-bin PATH   virtiofsd executable (default: /usr/libexec/virtiofsd)
  --work-dir PATH     Work directory (default: /tmp/asterinas-virtiofs)
  --cache-mode MODE   virtiofsd cache mode (auto, always, never, metadata; default: auto)
  -h, --help          Show this help message
EOF
}

while (($# > 0)); do
    case "$1" in
        --daemon-bin|--work-dir|--cache-mode)
            [[ $# -ge 2 ]] || { echo "missing argument for $1" >&2; exit 2; }
            case "$1" in
                --daemon-bin) daemon_bin=$2 ;;
                --work-dir) work_dir=$2 ;;
                --cache-mode) cache_mode=$2 ;;
            esac
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "unknown option: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

# Keep this socket path in sync with the paths generated by tools/qemu_args.sh.
socket=$work_dir/vfs.sock
shared_dir=$work_dir/shared
log_file=$work_dir/virtiofsd.log

if [[ -L "$work_dir" || (-e "$work_dir" && ! -d "$work_dir") ]]; then
    echo "work directory is not a safe directory: $work_dir" >&2
    exit 1
fi
install -d -m 700 "$work_dir"

work_dir_owner=$(stat -c '%u' "$work_dir")
work_dir_mode=$(stat -c '%a' "$work_dir")
if [[ "$work_dir_owner" != "$(id -u)" || "$work_dir_mode" != "700" ]]; then
    echo "work directory must be owned by the current user with mode 700: $work_dir" >&2
    exit 1
fi

if [[ -L "$shared_dir" || (-e "$shared_dir" && ! -d "$shared_dir") ]]; then
    echo "shared directory is not a safe directory: $shared_dir" >&2
    exit 1
fi
install -d -m 700 "$shared_dir"

if [[ -L "$socket" || -L "$log_file" ]]; then
    echo "socket or log path must not be a symlink" >&2
    exit 1
fi
rm -f "$socket"

exec "$daemon_bin" \
    --shared-dir "$shared_dir" \
    --socket-path "$socket" \
    --cache "$cache_mode" \
    >"$log_file" 2>&1
