[book]
authors = ["The Asterinas authors"]
language = "en"
multilingual = false
src = "src"
title = "The Asterinas Book"

[build]
create-missing = false

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"

[output.html.playground]
editable = false         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = false     # displays line numbers for editable code
runnable = false         # displays a run button for rust code

# https://gitlab.com/tglman/mdbook-variables
[preprocessor.variables]
use_env = true

[preprocessor.variables.variables]
# ENV_LATEST_TAG: curl -s 'https://api.github.com/repos/asterinas/asterinas/tags' | jq -r '.[0].name' | sed 's/v//'
