# template
[components]
std = { name = "jinux-std" }
pci = { name = "jinux-pci" }
virtio = { name = "jinux-virtio" }
input = { name = "jinux-input" }
block = { name = "jinux-block" }
time = { name = "jinux-time" }
main = { name = "jinux" }

[whitelist]
[whitelist.std.run_first_process]
main = true
