name: Cargo check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: asterinas/asterinas:0.3.1
    steps:
      - run: echo "Running in asterinas/asterinas:0.3.1"

      - uses: actions/checkout@v3
      
      - run: make install_osdk

      - name: Check
        id: check
        run: make check
