name: Cargo check

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  test:
    runs-on: ubuntu-latest
    container: jinuxdev/jinux:0.1.2
    steps:
      - run: echo "Running in jinuxdev/jinux:0.1.2"

      - uses: actions/checkout@v3

      - name: Check
        id: check
        run: make check
