name: Framework Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: asterinas/asterinas:0.4.0
    steps:
      - run: echo "Running in asterinas/asterinas:0.4.0"

      - uses: actions/checkout@v4
      
      - run: make install_osdk

      - run: make update_initramfs

      - name: Unit test
        id: test
        run: cd framework/aster-frame && cargo osdk test