name: Integration test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: jinuxdev/jinux:0.2.1
    steps:
      - run: echo "Running in jinuxdev/jinux:0.2.1"

      - uses: actions/checkout@v3

      - name: Boot Test (Multiboot)
        id: boot_test_mb
        run: RUSTFLAGS="-C opt-level=1" make run AUTO_TEST=dummy ENABLE_KVM=0 BOOT_PROTOCOL=multiboot

      - name: Boot Test (Multiboot2)
        id: boot_test_mb2
        run: RUSTFLAGS="-C opt-level=1" make run AUTO_TEST=dummy ENABLE_KVM=0 BOOT_PROTOCOL=multiboot2

      - name: Syscall Test (Linux Boot Protocol)
        id: syscall_test_linux
        run: RUSTFLAGS="-C opt-level=1" make run AUTO_TEST=syscall ENABLE_KVM=0 BOOT_PROTOCOL=linux

      # TODO: include the integration tests for MicroVM, which is not ready yet.
