name: OSDK CI

on:
  pull_request:
    paths:
      - osdk/**
  push:
    branches:
      - main

jobs:
  osdk-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: asterinas/asterinas:0.3.0
    steps:
      - run: echo "Running in asterinas/asterinas:0.3.0"

      - uses: actions/checkout@v3

      - name: Lint
        id: lint
        run: cd osdk && cargo clippy -- -D warnings

      - name: Unit test
        id: unit_test
        run: cd osdk && cargo build && cargo test
