name: Publish Docker images

on:
  workflow_dispatch:
  push:
    paths:
      - DOCKER_IMAGE_VERSION
    branches:
      - main

jobs:
  push_osdk_image:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup and Check
        uses: ./.github/actions/docker
        id: setup-check
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}
          image_name: 'osdk'

      - name: Build and push the OSDK development image
        if: ${{ steps.setup-check.outputs.is_existed == 'false' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./osdk/tools/docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: asterinas/osdk:${{ steps.setup-check.outputs.image_version }}
          build-args: |
            ASTER_RUST_VERSION=${{ steps.setup-check.outputs.rust_version }}

  push_osdk_tdx_image:
    needs: push_osdk_image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup and Check
        uses: ./.github/actions/docker
        id: setup-check
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}
          image_name: 'osdk-tdx'

      - name: Build and push the OSDK development image for Intel TDX
        if: ${{ steps.setup-check.outputs.is_existed == 'false' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./osdk/tools/docker/tdx/Dockerfile
          platforms: linux/amd64
          push: true
          tags: asterinas/osdk:${{ steps.setup-check.outputs.image_version }}-tdx
          build-args: |
            BASE_VERSION=${{ steps.setup-check.outputs.image_version }}

  push_nix_image:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - name: Setup and Check
        uses: ./.github/actions/docker
        id: setup-check
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}
          image_name: 'nix'

      - name: Build and push the Nix image
        if: ${{ steps.setup-check.outputs.is_existed == 'false' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./tools/docker/nix/Dockerfile
          platforms: linux/amd64
          push: true
          tags: asterinas/asterinas:${{ steps.setup-check.outputs.image_version }}-nix

  push_asterinas_image:
    needs:
      - push_osdk_image
      - push_nix_image
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - name: Setup and Check
        uses: ./.github/actions/docker
        id: setup-check
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}
          image_name: 'asterinas'

      - name: Build and push the Asterinas development image
        if: ${{ steps.setup-check.outputs.is_existed == 'false' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./tools/docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: asterinas/asterinas:${{ steps.setup-check.outputs.image_version }}
          build-args: |
            BASE_VERSION=${{ steps.setup-check.outputs.image_version }}

  push_asterinas_tdx_image:
    needs: push_asterinas_image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup and Check
        uses: ./.github/actions/docker
        id: setup-check
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}
          image_name: 'asterinas-tdx'

      - name: Build and push the Asterinas development image for Intel TDX
        if: ${{ steps.setup-check.outputs.is_existed == 'false' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./tools/docker/tdx/Dockerfile
          platforms: linux/amd64
          push: true
          tags: asterinas/asterinas:${{ steps.setup-check.outputs.image_version }}-tdx
          build-args: |
            BASE_VERSION=${{ steps.setup-check.outputs.image_version }}
