name: Syscall test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  test:
    runs-on: ubuntu-latest
    container: jinuxdev/jinux:0.1.1
    steps:
      - run: echo "Running in jinuxdev/jinux:0.1.1"

      - uses: actions/checkout@v3

      - name: Syscall Test
        id: syscall_test
        run: RUSTFLAGS="-C opt-level=1" make run AUTO_SYSCALL_TEST=1 ENABLE_KVM=0
