name: Test Asterinas

on:
  pull_request:
  push:
    branches:
      - main
  # Schedule to run on every day at 22:00 UTC (06:00 Beijing Time)
  schedule:
    - cron: '0 22 * * *'

jobs:
  lint:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: asterinas/asterinas:0.8.1
    steps:
      - run: echo "Running in asterinas/asterinas:0.8.1"

      - uses: actions/checkout@v4

      - name: Check
        id: check
        run: make check

  build-initrd:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v28

      - name: Restore and Cache Nix Store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', 'flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never

      - name: Build Initrd
        run: |
          nix build .#initrd -L

      - name: Upload Initrd
        uses: actions/upload-artifact@v4
        with:
          name: initrd.gz
          path: result/initrd.gz
          compression-level: 0  # initrd.gz is already compressed

  unit-test:
    needs: build-initrd
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: asterinas/asterinas:0.8.1
    env:
      PREBUILT_INITRAMFS: result/initrd.gz
    steps:
      - run: echo "Running in asterinas/asterinas:0.8.1"

      - uses: actions/checkout@v4

      - name: Download Initrd
        uses: actions/download-artifact@v4
        with:
          name: initrd.gz
          path: result

      - name: Usermode Unit test
        id: usermode_unit_test
        run: make test

      - name: Ktest Unit Test
        id: ktest_unit_test
        run: make ktest

      # TODO: add component check.

  integration-test:
    strategy:
      fail-fast: false
      matrix:
        initrd:
          - label: "Makefile initrd"
            path: ""
          - label: "Nix initrd"
            path: result/initrd.gz

    name: integration-test (${{ matrix.initrd.label }})
    needs: build-initrd
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: asterinas/asterinas:0.8.1
      options: --device=/dev/kvm
    env:
      PREBUILT_INITRAMFS: ${{ matrix.initrd.path }}
    steps:
      - run: echo "Running in asterinas/asterinas:0.8.1"

      - uses: actions/checkout@v4

      - name: Download Initrd
        if: ${{ matrix.initrd.path != '' }}
        uses: actions/download-artifact@v4
        with:
          name: initrd.gz
          path: result

      - name: SMP Boot Test (Multiboot)
        id: boot_test_mb
        run: make run AUTO_TEST=boot ENABLE_KVM=1 BOOT_PROTOCOL=multiboot RELEASE=1 SMP=4

      - name: SMP Boot Test (Linux Legacy 32-bit Boot Protocol)
        id: boot_test_linux_legacy32
        run: make run AUTO_TEST=boot ENABLE_KVM=1 BOOT_PROTOCOL=linux-legacy32 RELEASE=1 SMP=4

      - name: Syscall Test (Linux EFI Handover Boot Protocol) (Debug Build)
        id: syscall_test
        run: make run AUTO_TEST=syscall ENABLE_KVM=1 BOOT_PROTOCOL=linux-efi-handover64 RELEASE=0

      - name: Syscall Test at Ext2 (MicroVM)
        id: syscall_test_at_ext2
        run: make run AUTO_TEST=syscall SYSCALL_TEST_DIR=/ext2 ENABLE_KVM=1 SCHEME=microvm RELEASE=1

      - name: Syscall Test at Exfat (Multiboot2) (without KVM enabled)
        id: syscall_test_at_exfat_linux
        run: |
          make run AUTO_TEST=syscall \
            SYSCALL_TEST_DIR=/exfat EXTRA_BLOCKLISTS_DIRS=blocklists.exfat \
            ENABLE_KVM=0 BOOT_PROTOCOL=multiboot2 RELEASE=1

      - name: SMP Syscall Test (Multiboot2)
        id: smp_syscall_test_mb2
        run: make run AUTO_TEST=syscall ENABLE_KVM=1 BOOT_PROTOCOL=multiboot2 RELEASE=1 SMP=4

      - name: General Test (Linux EFI Handover Boot Protocol)
        id: test_linux
        run: make run AUTO_TEST=test ENABLE_KVM=1 BOOT_PROTOCOL=linux-efi-handover64 RELEASE=1

      - name: SMP General Test (Multiboot2)
        id: smp_test_mb2
        run: make run AUTO_TEST=test ENABLE_KVM=1 BOOT_PROTOCOL=multiboot2 RELEASE=1 SMP=4

  integration-test-tdx:
    if: github.event_name == 'schedule'
    runs-on: self-hosted
    timeout-minutes: 30
    container:
      image: asterinas/asterinas:0.8.1-tdx
      options: --device=/dev/kvm --privileged
    env:
      # Need to set up proxy since the self-hosted CI server is located in China,
      # which has poor network connection to the official Rust crate repositories.
      RUSTUP_DIST_SERVER: https://mirrors.ustc.edu.cn/rust-static
      RUSTUP_UPDATE_ROOT: https://mirrors.ustc.edu.cn/rust-static/rustup
    steps:
      - run: echo "Running in asterinas/asterinas:0.8.1-tdx"
      - uses: actions/checkout@v4
      - name: Set up the environment
        run: |
          chmod +x test/benchmark/bench_linux_and_aster.sh
          # Set up git due to the network issue on the self-hosted runner
          git config --global --add safe.directory /__w/asterinas/asterinas
          git config --global http.sslVerify false
          git config --global http.version HTTP/1.1
      - name: Boot Test (Linux EFI Handover Boot Protocol)
        uses: nick-invision/retry@v2
        id: boot_test_linux_efi_handover64
        with:
          timeout_minutes: 20
          max_attempts: 3
          command: make run AUTO_TEST=boot INTEL_TDX=1

      - name: Syscall Test (Linux EFI Handover Boot Protocol)
        uses: nick-invision/retry@v2
        id: syscall_test
        with:
          timeout_minutes: 20
          max_attempts: 3
          command: make run AUTO_TEST=syscall INTEL_TDX=1

      - name: Syscall Test at Exfat
        uses: nick-invision/retry@v2
        id: syscall_test_at_exfat_linux
        with:
          timeout_minutes: 20
          max_attempts: 3
          command: make run AUTO_TEST=syscall SYSCALL_TEST_DIR=/exfat EXTRA_BLOCKLISTS_DIRS=blocklists.exfat INTEL_TDX=1

      - name: General Test (Linux EFI Handover Boot Protocol)
        uses: nick-invision/retry@v2
        id: test_linux
        with:
          timeout_minutes: 20
          max_attempts: 3
          command: make run AUTO_TEST=test INTEL_TDX=1
