# Edit this configuration file to define what should be installed on
# your system. Help is available in the configuration.nix(5) man page, on
# https://search.nixos.org/options and in the NixOS manual (`nixos-help`).

# The content of this file largely mirrors or aligns with the output
# generated by `nixos-generate-config`.

{ config, lib, pkgs, ... }: {
  # Do not change these imports, which describe system-wide settings for AsterNixOS.
  imports = [ ./aster_configuration.nix ];

  networking.hostName = "asterinas"; # Define your hostname.

  # Uncomment the two options below to enable the X11 (X.Org) desktop (XFCE).
  # services.xserver.enable = true;
  # services.xserver.desktopManager.xfce.enable = true;

  # Uncomment the following line to enable Podman.
  # virtualisation.podman.enable = true;

  # List packages installed in system profile.
  # You can use https://search.nixos.org/ to find more packages (and options).
  environment.systemPackages = with pkgs; [ hello-asterinas ];

  system.nixos.distroName = "Asterinas NixOS";

  # This option defines the first version of NixOS you have installed on this particular machine,
  # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
  #
  # Most users should NEVER change this value after the initial install, for any reason,
  # even if you've upgraded your system to a new NixOS release.
  #
  # This value does NOT affect the Nixpkgs version your packages and OS are pulled from,
  # so changing it will NOT upgrade your system - see https://nixos.org/manual/nixos/stable/#sec-upgrading for how
  # to actually do that.
  #
  # This value being lower than the current NixOS release does NOT mean your system is
  # out of date, out of support, or vulnerable.
  #
  # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
  # and migrated your data accordingly.
  #
  # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "25.05"; # Did you read the comment?
}
